### PR TITLE
fix(firestore-send-email): SendGrid v3 issues

### LINKED ISSUE #2004: 🐛 [firestore-send-email] The `delivery.info` entry is missing after upgrading to 0.1.32.
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs for a **specific extension in this repository**.
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

- For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
  with the firebase tag.
- For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
  google group.
- To file a bug against the Firebase Extensions platform, or for an issue affecting multiple extensions, please reach out to
  [Firebase support](https://firebase.google.com/support/troubleshooter/contact/) directly.

### [REQUIRED] Step 2: Describe your configuration

- Extension name: **firestore-send-email**
- Extension version: **0.1.32**
- Configuration values (redact info where appropriate):
  - **DEFAULT_FROM=kingu.dev <support@kingu.dev>**
  - **DEFAULT_REPLY_TO=support@kingu.dev**
  - **MAIL_COLLECTION=mails_v1**
  - **SMTP_CONNECTION_URI=smtps://apikey@smtp.sendgrid.net:465**
  - **SMTP_PASSWORD=projects/${param:PROJECT_NUMBER}/secrets/firestore-send-email-SMTP_PASSWORD/versions/latest**
  - **TEMPLATES_COLLECTION=mailTemplates_v1**
  - **TTL_EXPIRE_TYPE=never**
  - **TTL_EXPIRE_VALUE=1**

### [REQUIRED] Step 3: Describe the problem

After upgrading to 0.1.32, `delivery.info.accepted`, `delivery.info.messageId`, `delivery.info..response` is missing.

#### Steps to reproduce:

1. Upgraded to 0.1.32

##### Expected result

`delivery.info` should not be missing.

##### Actual result

v0.1.31
スクリーンショット 2024-03-26 16 06 18

v0.1.32
スクリーンショット 2024-03-26 16 06 42

### PR DESCRIPTION
**Pull request by jauntybrain**
- Use new SendGrid (v3) transport only when payload body contains `sendGrid` field
-  Fix an issue where `text` or `html` fields were `null` and not `undefined` which was resulting in an error.

Resolves #2004.

### CODE REVIEW

File: firestore-send-email/functions/src/helpers.ts [hunk 1]
```diff
@@ -70,17 +70,29 @@ export function setSmtpCredentials(config: Config) {
         pass: decodeURIComponent(url.password),
       },
     });
-  } else if (checkSendGrid(url.hostname)) {
+  } else {
```
Comment (pr-Mais) [inline firestore-send-email/functions/src/helpers.ts:73]: if not needed remove completely

File: firestore-send-email/functions/src/index.ts [hunk 2]
```diff
@@ -282,6 +286,7 @@ async function deliver(
   }
 
   logs.attemptingDelivery(ref);
+  functions.logger.warn("here 0");
```
Comment (pr-Mais) [inline firestore-send-email/functions/src/index.ts:289]:
```suggestion
```

File: firestore-send-email/functions/src/index.ts [hunk 3]
```diff
@@ -290,18 +295,37 @@ async function deliver(
   };
 
   try {
+    functions.logger.warn("here 1");
```
Comment (pr-Mais) [inline firestore-send-email/functions/src/index.ts:298]:
```suggestion
```

File: firestore-send-email/functions/src/index.ts [hunk 4]
```diff
@@ -325,11 +350,15 @@ async function deliver(
...
     update["delivery.info"] = info;
+    functions.logger.warn("here 7");
     logs.delivered(ref, info);
+    functions.logger.warn("here 8");
   } catch (e) {
+    functions.logger.warn("here 9");
     update["delivery.state"] = "ERROR";
     update["delivery.error"] = e.toString();
     logs.deliveryError(ref, e);
+    functions.logger.warn("here 10");
```
Comment (pr-Mais) [inline firestore-send-email/functions/src/index.ts:361]:
```suggestion
```

File: firestore-send-email/functions/src/index.ts [hunk 5]
```diff
@@ -325,11 +350,15 @@ async function deliver(
 
     update["delivery.state"] = "SUCCESS";
     update["delivery.info"] = info;
+    functions.logger.warn("here 7");
     logs.delivered(ref, info);
+    functions.logger.warn("here 8");
   } catch (e) {
+    functions.logger.warn("here 9");
```
Comment (pr-Mais) [inline firestore-send-email/functions/src/index.ts:357]:
```suggestion
```

File: firestore-send-email/functions/src/index.ts [hunk 6]
```diff
@@ -325,11 +350,15 @@ async function deliver(
 
     update["delivery.state"] = "SUCCESS";
     update["delivery.info"] = info;
+    functions.logger.warn("here 7");
     logs.delivered(ref, info);
+    functions.logger.warn("here 8");
```
Comment (pr-Mais) [inline firestore-send-email/functions/src/index.ts:355]:
```suggestion
```

File: firestore-send-email/functions/src/index.ts [hunk 7]
```diff
@@ -325,11 +350,15 @@ async function deliver(
 
     update["delivery.state"] = "SUCCESS";
     update["delivery.info"] = info;
+    functions.logger.warn("here 7");
```
Comment (pr-Mais) [inline firestore-send-email/functions/src/index.ts:353]:
```suggestion
```

File: firestore-send-email/functions/src/index.ts [hunk 8]
```diff
@@ -315,6 +339,7 @@ async function deliver(
         mail_settings: payload.sendGrid?.mailSettings || {},
       }),
     });
+    functions.logger.warn("here 6");
```
Comment (pr-Mais) [inline firestore-send-email/functions/src/index.ts:342]:
```suggestion
```

File: firestore-send-email/functions/src/index.ts [hunk 9]
```diff
@@ -338,6 +367,7 @@ async function deliver(
     // since the email sending will have been attempted regardless of what the
     // delivery state was at that point, so we just update the state to reflect
     // the result of the last attempt so as to not potentially cause duplicate sends.
+    functions.logger.warn("here 11");
```
Comment (pr-Mais) [inline firestore-send-email/functions/src/index.ts:370]:
```suggestion
```

File: firestore-send-email/functions/src/index.ts [hunk 10]
```diff
@@ -290,18 +295,37 @@ async function deliver(
...
-    // either a text or html content, or if the payload contains a SendGrid Dynamic Template.
-    verifySendGridContent(payload);
-
     if (!payload.to.length && !payload.cc.length && !payload.bcc.length) {
       throw new Error(
         "Failed to deliver email. Expected at least 1 recipient."
       );
     }
 
+    functions.logger.warn("here 2");
```
Comment (pr-Mais) [inline firestore-send-email/functions/src/index.ts:307]:
```suggestion
```

File: firestore-send-email/functions/src/index.ts [hunk 11]
```diff
@@ -290,18 +295,37 @@ async function deliver(
...
+
+    // Switch to SendGrid transport if SendGrid config is provided
+    if (payload.sendGrid) {
+      functions.logger.warn("here 3");
```
Comment (pr-Mais) [inline firestore-send-email/functions/src/index.ts:311]:
```suggestion
```

File: firestore-send-email/functions/src/index.ts [hunk 12]
```diff
@@ -290,18 +295,37 @@ async function deliver(
...
-
     if (!payload.to.length && !payload.cc.length && !payload.bcc.length) {
       throw new Error(
         "Failed to deliver email. Expected at least 1 recipient."
       );
     }
 
+    functions.logger.warn("here 2");
+
+    // Switch to SendGrid transport if SendGrid config is provided
```
Comment (pr-Mais) [inline firestore-send-email/functions/src/index.ts:309]:
```suggestion
    // Switch to SendGrid transport if SendGrid config is provided.
    // This will automatically use SendGrid v3 API.
```

**Review by pr-Mais — CHANGES_REQUESTED** [review]
