### PR TITLE
fix: add support for SendGrid categories and streamline SendGrid detection

### LINKED ISSUE #2053: 🐛 [firestore-send-email] Could not send category to sendGrid
- Extension name: **firestore-send-email**
- Extension version: **latest** 

 Describe the problem

#### Steps to reproduce:

I have tried to send an email with the following headers via the firestore documet
```
  "headers": {
    "X-SMTPAPI": "{\"category\": [\"Example Category\"]}"
  }
```

but i dont see the categories in sendGrid

is there any other option to send category to their  side?

##### Expected result

Send grid will be able to get categories 

##### Actual result

could not categirieze emails

### PR DESCRIPTION
**Pull request by Gustolandia**
This PR addresses the following improvements and fixes for the Firestore-Send-Email extension:

Enhancement: Increase in Payload Fields
Developers can now include categories.
Introduced a dynamic method for detecting SendGrid usage based on the SMTP_CONNECTION_URI. 
Bug Fix: Categories Not Being Sent
The categories field was not properly passed to the SendGrid API in the previous implementation.
Modified the email preparation and transport logic to ensure that the categories field is passed as per SendGrid's requirements.
Refactored Code and Tests
Removed the unused nodemailer-sendgrid dependency to simplify the codebase and avoid confusion.
Updated helpers.ts and corresponding tests in helpers.test.ts to support the new dynamic SendGrid detection.
Added logs to indicate whether the email is being sent via SendGrid or the standard transport.
Changes:

Code Changes:
Updated src/index.ts to dynamically detect SendGrid and utilize the appropriate sending method.
Modified src/helpers.ts to add an isSendGrid function and streamline SMTP transport setup.
Updated src/types.ts to reflect the additional flexibility in payload fields.
Tests:
Refactored helpers.test.ts to test the new isSendGrid function.
Added additional test cases to validate the proper handling of various SMTP connection URIs.
Dependencies:
Removed nodemailer-sendgrid from package.json and package-lock.json.
How to Test:

Deploy the updated extension in a local Firebase project with the emulators enabled.
Use the following payload in the Firestore mail collection:
```
{
  "to": ["example@example.com"],
  "categories": ["Example_Category"],
  "message": {
    "subject": "Final Test for Categories",
    "text": "This is a test email to see if categories work.",
    "html": "<strong>This is a test email to see if categories work.</strong>"
  }
}
```

Verify:
The email is successfully sent.
The categories field is correctly registered in SendGrid.
Logs indicate whether the SendGrid or standard transport was used.

Linked Issues:

Resolves #2053
Reviewer Checklist:
 Code adheres to the existing style and conventions.
 New features are covered by unit tests.
 Breaking changes are documented and communicated effectively.

### CODE REVIEW

File: firestore-send-email/functions/src/helpers.ts [hunk 1]
```diff
@@ -79,12 +74,6 @@
...
-export function setSendGridTransport(config: Config) {
-  const { smtpPassword } = config;
-
-  const options: sg.SendgridOptions = {
-    apiKey: smtpPassword,
-  };
-
-  return createTransport(sg(options));
+export function isSendGrid(config: Config): boolean {
+  return config.smtpConnectionUri.includes("sendgrid.net");
```
[the remark this answers is not in the document]
Comment (Gustolandia) [reply firestore-send-email/functions/src/helpers.ts]: I have corrected this

File: firestore-send-email/functions/src/index.ts [hunk 2]
```diff
@@ -294,45 +323,44 @@ async function deliver(
...
-        to: payload.to,
-        cc: payload.cc,
-        bcc: payload.bcc,
-        headers: payload.headers || {},
-        template_id: payload.sendGrid?.templateId,
-        dynamic_template_data: payload.sendGrid?.dynamicTemplateData || {},
-        mail_settings: payload.sendGrid?.mailSettings || {},
-      }),
+    // Log the payload and response
+    console.log("Final Payload Sent:", {
```
Comment (cabljac) [inline firestore-send-email/functions/src/index.ts:359]: How come we're logging? If we log we should use the logger from firebase-functions

If this was to debug, it should be removed

File: firestore-send-email/functions/src/index.ts [hunk 3]
```diff
@@ -343,22 +371,20 @@ async function deliver(
...
     update["delivery.state"] = "ERROR";
     update["delivery.error"] = e.toString();
     logs.deliveryError(ref, e);
   }
 
-  // Wrapping in transaction to allow for automatic retries (#48)
+  // Update the Firestore document transactionally to allow retries
   return admin.firestore().runTransaction((transaction) => {
-    // We could check state here is still PROCESSING, but we don't
-    // since the email sending will have been attempted regardless of what the
```
Comment (cabljac) [inline firestore-send-email/functions/src/index.ts:359]: why are we removing code comments like this?

File: firestore-send-email/functions/src/index.ts [hunk 4]
```diff
@@ -294,45 +323,44 @@ async function deliver(
...
-        }
-      }
+    let result;
 
-      // If the SMTP provider is SendGrid, we need to check if the payload contains
-      // either a text or html content, or if the payload contains a SendGrid Dynamic Template.
-      verifySendGridContent(payload);
+    // Automatically detect SendGrid
+    if (isSendGrid(config)) {
+      console.log("Using SendGrid for email delivery.");
```
Comment (cabljac) [inline firestore-send-email/functions/src/index.ts:340]: use firebase-functions for logging if needed. Remove these if they were for debugging/testing purposes, otherwise we're going to flood cloud logging/cost them more

File: firestore-send-email/functions/src/index.ts [hunk 5]
```diff
@@ -294,45 +323,44 @@ async function deliver(
...
+      result = await sendWithSendGrid(payload); // Use the SendGrid-specific function
+    } else {
+      console.log("Using standard transport for email delivery.");
```
Comment (cabljac) [inline firestore-send-email/functions/src/index.ts:343]: remove if for debugging purposes

File: firestore-send-email/functions/src/helpers.ts [hunk 6]
```diff
@@ -79,12 +74,14 @@ export function setSmtpCredentials(config: Config) {
...
-
-  return createTransport(sg(options));
+export function isSendGrid(config: Config): boolean {
+  try {
+    const url = new URL(config.smtpConnectionUri);
+    // Ensure the hostname matches exactly
+    return url.hostname === "smtp.sendgrid.net";
+  } catch (err) {
+    // Log error for debugging if URL parsing fails
+    console.error("Invalid SMTP_CONNECTION_URI:", err.message);
```
Comment (cabljac) [inline firestore-send-email/functions/src/helpers.ts:84]: use firebase-functions logger

**Review by cabljac — DISMISSED** [review]
Generally looks good! a few comments about logs/deleting code comments to look at

File: firestore-send-email/functions/package.json
Comment (CorieW) [inline firestore-send-email/functions/package.json:1]: `"nodemailer-sendgrid": "^1.0.3"` is very old and vulnerable, so could it be removed alongside `"@types/nodemailer-sendgrid": "^1.0.3"`?

Comment (Gustolandia) [reply firestore-send-email/functions/package.json:1]: Done. Thanks

File: firestore-send-email/functions/__tests__/helpers.test.ts [hunk 7]
```diff
@@ -185,48 +143,52 @@ describe("set server credentials helper function", () => {
...
       location: "",
       mailCollection: "",
       defaultFrom: "",
     };
 
-    expect(regex.test(config.smtpConnectionUri)).toBe(true);
+    expect(isSendGrid(config)).toBe(true);
   });
 
-  test("return invalid smtpConnectionUri credentials with invalid seprator", () => {
```
Comment (pr-Mais) [inline firestore-send-email/functions/__tests__/helpers.test.ts:207]: We should keep this test

File: firestore-send-email/functions/__tests__/helpers.test.ts [hunk 8]
```diff
@@ -153,30 +134,7 @@ describe("set server credentials helper function", () => {
     expect(regex.test(config.smtpConnectionUri)).toBe(true);
   });
 
-  test("return valid smtpConnectionUri credentials with valid special chars in connectionUri password", () => {
```
Comment (pr-Mais) [inline firestore-send-email/functions/__tests__/helpers.test.ts:156]: why this test is removed?

File: firestore-send-email/functions/src/index.ts [hunk 9]
```diff
@@ -253,39 +250,79 @@ async function preparePayload(payload: QueuePayload): Promise<QueuePayload> {
...
+  logs.info("SendGrid message payload constructed", { msg });
+
+  // Send the message using SendGrid's API
+  return sgMail.send(msg);
 }
 
 async function deliver(
   ref: admin.firestore.DocumentReference<QueuePayload>
 ): Promise<void> {
+  // Fetch the Firestore document
```
Comment (pr-Mais) [inline firestore-send-email/functions/src/index.ts:310]:
```suggestion
```

File: firestore-send-email/functions/src/index.ts [hunk 10]
```diff
@@ -294,47 +331,75 @@ async function deliver(
...
+            typeof payload.message?.text === "string"
+              ? payload.message?.text
+              : undefined,
+          html:
+            typeof payload.message?.html === "string"
+              ? payload.message?.html
+              : undefined,
+          categories: payload.categories,
+          headers: payload.headers,
+        },
```
Comment (pr-Mais) [inline firestore-send-email/functions/src/index.ts:366]: assign the payload to a variable to avoid duplication

File: firestore-send-email/functions/src/index.ts [hunk 11]
```diff
@@ -343,17 +408,19 @@ async function deliver(
...
     logs.delivered(ref, info);
   } catch (e) {
+    // Update Firestore document to indicate failure
     update["delivery.state"] = "ERROR";
     update["delivery.error"] = e.toString();
     logs.deliveryError(ref, e);
   }
 
-  // Wrapping in transaction to allow for automatic retries (#48)
+  // Update the Firestore document transactionally to allow retries
```
Comment (pr-Mais) [inline firestore-send-email/functions/src/index.ts:423]: keep old comment as it's referencing an issue

File: firestore-send-email/functions/src/types.ts [hunk 12]
```diff
@@ -82,4 +82,14 @@ export interface QueuePayload {
   replyTo?: string;
   headers?: any;
   attachments: Attachment[];
+  categories?: string[];
```
Comment (pr-Mais) [inline firestore-send-email/functions/src/types.ts:85]: is it needed here?

**Review by pr-Mais — CHANGES_REQUESTED** [review]

File: firestore-send-email/functions/src/index.ts (hunk 11 above)
Comment (Gustolandia) [reply firestore-send-email/functions/src/index.ts:423]: Added issue to new comment.

File: firestore-send-email/functions/src/types.ts (hunk 12 above)
Comment (Gustolandia) [reply firestore-send-email/functions/src/types.ts:85]: Yes.
